-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\untitled\Subsystem.vhd
-- Created: 2021-06-08 00:09:04
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0
-- Target subsystem base rate: 0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: untitled/Subsystem
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem IS
  PORT( clk                               :   in    std_logic;
        In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        reset                             :   in   std_logic;
		done_step		                  : out std_logic;
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
        );
END Subsystem;


ARCHITECTURE rtl OF Subsystem IS

  -- Signals
  SIGNAL In1_signed                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL Data_Type_Conversion_out1        : signed(7 DOWNTO 0);  -- int8
  
  type states is (ENTER, DONE);
  signal delay_state : states := ENTER;

BEGIN

    process(clk,reset)

	begin
		if reset = '0' then
		
            Out1 <= "00000000";
            
		elsif clk'event and clk = '1' then
            
            case delay_state is
			when ENTER =>
			    done_step <= '0';
                In1_signed <= signed(In1);
                Data_Type_Conversion_out1 <= In1_signed(7 DOWNTO 0);
                Out1 <= std_logic_vector(Data_Type_Conversion_out1);
                delay_state <= DONE;
                
            when DONE =>    
                done_step <= '1';
                delay_state <= ENTER;
            end case;
        end if;
    end process;

END rtl;

