-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\sine_fit\fit_qam.vhd
-- Created: 2020-10-27 18:28:56
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fit_qam
-- Source Path: sine_fit/fit_qam
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY fit_qam IS
  PORT( In1                               :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64_En15
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END fit_qam;


ARCHITECTURE rtl OF fit_qam IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(63 DOWNTO 0);  -- ufix64_En15
  SIGNAL Constant1_out1                   : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Product_out1                     : unsigned(69 DOWNTO 0);  -- ufix70_En15
  SIGNAL Constant3_out1                   : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL Add_add_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En15
  SIGNAL Add_add_cast_1                   : unsigned(95 DOWNTO 0);  -- ufix96_En15
  SIGNAL Add_out1                         : unsigned(95 DOWNTO 0);  -- ufix96_En15
  SIGNAL Data_Type_Conversion_out1        : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  In1_unsigned <= unsigned(In1);

  Constant1_out1 <= to_unsigned(16#3F#, 6);

  Product_out1 <= In1_unsigned * Constant1_out1;

  Constant3_out1 <= to_unsigned(16#7F#, 7);

  Add_add_cast <= resize(Product_out1, 96);
  Add_add_cast_1 <= resize(Constant3_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  Add_out1 <= Add_add_cast + Add_add_cast_1;

  Data_Type_Conversion_out1 <= Add_out1(22 DOWNTO 15);

  Out1 <= std_logic_vector(Data_Type_Conversion_out1);

END rtl;

