-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\untitled\qam_math.vhd
-- Created: 2020-09-18 18:51:28
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: qam_math
-- Source Path: untitled/qam_math
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY qam_math IS
  PORT( Input                             :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
        Input1                            :   IN    std_logic_vector(1 DOWNTO 0);  -- sfix2
        Out1                              :   OUT   std_logic_vector(63 DOWNTO 0)  -- sfix64_En15
        );
END qam_math;


ARCHITECTURE rtl OF qam_math IS

  -- Signals
  SIGNAL Input_signed                     : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Input1_signed                    : signed(1 DOWNTO 0);  -- sfix2
  SIGNAL Product_out1                     : signed(33 DOWNTO 0);  -- sfix34_En15
  SIGNAL Add_add_cast                     : signed(63 DOWNTO 0);  -- sfix64_En15
  SIGNAL Add_add_cast_1                   : signed(63 DOWNTO 0);  -- sfix64_En15
  SIGNAL Add_out1                         : signed(63 DOWNTO 0);  -- sfix64_En15

BEGIN
  Input_signed <= signed(Input);

  Input1_signed <= signed(Input1);

  Product_out1 <= Input_signed * Input1_signed;

  Add_add_cast <= resize(Product_out1, 64);
  Add_add_cast_1 <= resize(Product_out1, 64);
  Add_out1 <= Add_add_cast + Add_add_cast_1;

  Out1 <= std_logic_vector(Add_out1);

END rtl;

