-- -------------------------------------------------------------
--
-- Module: demod_filter
-- Generated by MATLAB(R) 9.6 and Filter Design HDL Coder 3.1.5.
-- Generated on: 2021-09-18 17:11:14
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- FIRAdderStyle: tree
-- AddPipelineRegisters: on
-- Name: demod_filter
-- ResetAssertedLevel: Active-low
-- TestBenchStimulus: impulse step ramp chirp noise 
-- GenerateHDLTestBench: off

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 72
-- Stable            : Yes
-- Linear Phase      : Yes (Type 2)
-- Arithmetic        : fixed
-- Numerator         : s21,20 -> [-1 1)
-- Input             : s21,20 -> [-1 1)
-- Filter Internals  : Full Precision
--   Output          : s41,40 -> [-1 1)  (auto determined)
--   Product         : s38,40 -> [-1.250000e-01 1.250000e-01)  (auto determined)
--   Accumulator     : s41,40 -> [-1 1)  (auto determined)
--   Round Mode      : No rounding
--   Overflow Mode   : No overflow
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY demod_filter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(20 DOWNTO 0); -- sfix21_En20
         filter_out                      :   OUT   std_logic_vector(40 DOWNTO 0)  -- sfix41_En40
         );

END demod_filter;


----------------------------------------------------------------
--Module Architecture: demod_filter
----------------------------------------------------------------
ARCHITECTURE rtl OF demod_filter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(20 DOWNTO 0); -- sfix21_En20
  -- Constants
  CONSTANT coeff1                         : signed(20 DOWNTO 0) := to_signed(111100, 21); -- sfix21_En20
  CONSTANT coeff2                         : signed(20 DOWNTO 0) := to_signed(7782, 21); -- sfix21_En20
  CONSTANT coeff3                         : signed(20 DOWNTO 0) := to_signed(8056, 21); -- sfix21_En20
  CONSTANT coeff4                         : signed(20 DOWNTO 0) := to_signed(8312, 21); -- sfix21_En20
  CONSTANT coeff5                         : signed(20 DOWNTO 0) := to_signed(8576, 21); -- sfix21_En20
  CONSTANT coeff6                         : signed(20 DOWNTO 0) := to_signed(8826, 21); -- sfix21_En20
  CONSTANT coeff7                         : signed(20 DOWNTO 0) := to_signed(9098, 21); -- sfix21_En20
  CONSTANT coeff8                         : signed(20 DOWNTO 0) := to_signed(9336, 21); -- sfix21_En20
  CONSTANT coeff9                         : signed(20 DOWNTO 0) := to_signed(9596, 21); -- sfix21_En20
  CONSTANT coeff10                        : signed(20 DOWNTO 0) := to_signed(9826, 21); -- sfix21_En20
  CONSTANT coeff11                        : signed(20 DOWNTO 0) := to_signed(10065, 21); -- sfix21_En20
  CONSTANT coeff12                        : signed(20 DOWNTO 0) := to_signed(10271, 21); -- sfix21_En20
  CONSTANT coeff13                        : signed(20 DOWNTO 0) := to_signed(10498, 21); -- sfix21_En20
  CONSTANT coeff14                        : signed(20 DOWNTO 0) := to_signed(10676, 21); -- sfix21_En20
  CONSTANT coeff15                        : signed(20 DOWNTO 0) := to_signed(10891, 21); -- sfix21_En20
  CONSTANT coeff16                        : signed(20 DOWNTO 0) := to_signed(11084, 21); -- sfix21_En20
  CONSTANT coeff17                        : signed(20 DOWNTO 0) := to_signed(11301, 21); -- sfix21_En20
  CONSTANT coeff18                        : signed(20 DOWNTO 0) := to_signed(11503, 21); -- sfix21_En20
  CONSTANT coeff19                        : signed(20 DOWNTO 0) := to_signed(11745, 21); -- sfix21_En20
  CONSTANT coeff20                        : signed(20 DOWNTO 0) := to_signed(11766, 21); -- sfix21_En20
  CONSTANT coeff21                        : signed(20 DOWNTO 0) := to_signed(11994, 21); -- sfix21_En20
  CONSTANT coeff22                        : signed(20 DOWNTO 0) := to_signed(12159, 21); -- sfix21_En20
  CONSTANT coeff23                        : signed(20 DOWNTO 0) := to_signed(12279, 21); -- sfix21_En20
  CONSTANT coeff24                        : signed(20 DOWNTO 0) := to_signed(12426, 21); -- sfix21_En20
  CONSTANT coeff25                        : signed(20 DOWNTO 0) := to_signed(12551, 21); -- sfix21_En20
  CONSTANT coeff26                        : signed(20 DOWNTO 0) := to_signed(12670, 21); -- sfix21_En20
  CONSTANT coeff27                        : signed(20 DOWNTO 0) := to_signed(12782, 21); -- sfix21_En20
  CONSTANT coeff28                        : signed(20 DOWNTO 0) := to_signed(12879, 21); -- sfix21_En20
  CONSTANT coeff29                        : signed(20 DOWNTO 0) := to_signed(12963, 21); -- sfix21_En20
  CONSTANT coeff30                        : signed(20 DOWNTO 0) := to_signed(13034, 21); -- sfix21_En20
  CONSTANT coeff31                        : signed(20 DOWNTO 0) := to_signed(13102, 21); -- sfix21_En20
  CONSTANT coeff32                        : signed(20 DOWNTO 0) := to_signed(13140, 21); -- sfix21_En20
  CONSTANT coeff33                        : signed(20 DOWNTO 0) := to_signed(13200, 21); -- sfix21_En20
  CONSTANT coeff34                        : signed(20 DOWNTO 0) := to_signed(13239, 21); -- sfix21_En20
  CONSTANT coeff35                        : signed(20 DOWNTO 0) := to_signed(13243, 21); -- sfix21_En20
  CONSTANT coeff36                        : signed(20 DOWNTO 0) := to_signed(13278, 21); -- sfix21_En20
  CONSTANT coeff37                        : signed(20 DOWNTO 0) := to_signed(13278, 21); -- sfix21_En20
  CONSTANT coeff38                        : signed(20 DOWNTO 0) := to_signed(13243, 21); -- sfix21_En20
  CONSTANT coeff39                        : signed(20 DOWNTO 0) := to_signed(13239, 21); -- sfix21_En20
  CONSTANT coeff40                        : signed(20 DOWNTO 0) := to_signed(13200, 21); -- sfix21_En20
  CONSTANT coeff41                        : signed(20 DOWNTO 0) := to_signed(13140, 21); -- sfix21_En20
  CONSTANT coeff42                        : signed(20 DOWNTO 0) := to_signed(13102, 21); -- sfix21_En20
  CONSTANT coeff43                        : signed(20 DOWNTO 0) := to_signed(13034, 21); -- sfix21_En20
  CONSTANT coeff44                        : signed(20 DOWNTO 0) := to_signed(12963, 21); -- sfix21_En20
  CONSTANT coeff45                        : signed(20 DOWNTO 0) := to_signed(12879, 21); -- sfix21_En20
  CONSTANT coeff46                        : signed(20 DOWNTO 0) := to_signed(12782, 21); -- sfix21_En20
  CONSTANT coeff47                        : signed(20 DOWNTO 0) := to_signed(12670, 21); -- sfix21_En20
  CONSTANT coeff48                        : signed(20 DOWNTO 0) := to_signed(12551, 21); -- sfix21_En20
  CONSTANT coeff49                        : signed(20 DOWNTO 0) := to_signed(12426, 21); -- sfix21_En20
  CONSTANT coeff50                        : signed(20 DOWNTO 0) := to_signed(12279, 21); -- sfix21_En20
  CONSTANT coeff51                        : signed(20 DOWNTO 0) := to_signed(12159, 21); -- sfix21_En20
  CONSTANT coeff52                        : signed(20 DOWNTO 0) := to_signed(11994, 21); -- sfix21_En20
  CONSTANT coeff53                        : signed(20 DOWNTO 0) := to_signed(11766, 21); -- sfix21_En20
  CONSTANT coeff54                        : signed(20 DOWNTO 0) := to_signed(11745, 21); -- sfix21_En20
  CONSTANT coeff55                        : signed(20 DOWNTO 0) := to_signed(11503, 21); -- sfix21_En20
  CONSTANT coeff56                        : signed(20 DOWNTO 0) := to_signed(11301, 21); -- sfix21_En20
  CONSTANT coeff57                        : signed(20 DOWNTO 0) := to_signed(11084, 21); -- sfix21_En20
  CONSTANT coeff58                        : signed(20 DOWNTO 0) := to_signed(10891, 21); -- sfix21_En20
  CONSTANT coeff59                        : signed(20 DOWNTO 0) := to_signed(10676, 21); -- sfix21_En20
  CONSTANT coeff60                        : signed(20 DOWNTO 0) := to_signed(10498, 21); -- sfix21_En20
  CONSTANT coeff61                        : signed(20 DOWNTO 0) := to_signed(10271, 21); -- sfix21_En20
  CONSTANT coeff62                        : signed(20 DOWNTO 0) := to_signed(10065, 21); -- sfix21_En20
  CONSTANT coeff63                        : signed(20 DOWNTO 0) := to_signed(9826, 21); -- sfix21_En20
  CONSTANT coeff64                        : signed(20 DOWNTO 0) := to_signed(9596, 21); -- sfix21_En20
  CONSTANT coeff65                        : signed(20 DOWNTO 0) := to_signed(9336, 21); -- sfix21_En20
  CONSTANT coeff66                        : signed(20 DOWNTO 0) := to_signed(9098, 21); -- sfix21_En20
  CONSTANT coeff67                        : signed(20 DOWNTO 0) := to_signed(8826, 21); -- sfix21_En20
  CONSTANT coeff68                        : signed(20 DOWNTO 0) := to_signed(8576, 21); -- sfix21_En20
  CONSTANT coeff69                        : signed(20 DOWNTO 0) := to_signed(8312, 21); -- sfix21_En20
  CONSTANT coeff70                        : signed(20 DOWNTO 0) := to_signed(8056, 21); -- sfix21_En20
  CONSTANT coeff71                        : signed(20 DOWNTO 0) := to_signed(7782, 21); -- sfix21_En20
  CONSTANT coeff72                        : signed(20 DOWNTO 0) := to_signed(111100, 21); -- sfix21_En20

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 71); -- sfix21_En20
  SIGNAL product72                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp                         : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product71                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_1                       : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product70                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_2                       : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product69                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_3                       : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product68                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_4                       : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product67                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_5                       : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product66                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_6                       : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product65                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_7                       : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product64                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_8                       : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product63                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_9                       : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product62                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_10                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product61                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_11                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product60                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_12                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product59                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_13                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product58                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_14                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product57                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_15                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product56                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_16                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product55                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_17                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product54                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_18                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product53                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_19                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product52                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_20                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product51                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_21                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product50                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_22                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product49                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_23                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product48                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_24                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product47                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_25                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product46                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_26                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product45                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_27                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product44                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_28                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product43                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_29                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product42                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_30                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product41                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_31                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product40                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_32                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product39                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_33                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product38                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_34                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product37                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_35                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product36                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_36                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product35                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_37                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product34                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_38                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product33                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_39                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product32                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_40                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product31                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_41                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product30                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_42                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product29                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_43                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product28                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_44                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product27                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_45                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product26                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_46                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product25                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_47                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product24                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_48                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product23                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_49                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product22                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_50                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product21                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_51                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product20                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_52                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product19                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_53                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product18                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_54                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product17                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_55                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product16                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_56                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product15                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_57                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product14                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_58                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product13                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_59                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product12                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_60                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product11                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_61                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product10                        : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_62                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product9                         : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_63                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product8                         : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_64                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product7                         : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_65                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product6                         : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_66                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product5                         : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_67                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product4                         : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_68                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product3                         : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_69                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product2                         : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_70                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL product1                         : signed(37 DOWNTO 0); -- sfix38_En40
  SIGNAL mul_temp_71                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sum_final                        : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_1                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp                         : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_1                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_2                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_1                       : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_2                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_3                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_2                       : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_3                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_4                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_3                       : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_4                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_5                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_4                       : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_5                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_6                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_5                       : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_6                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_7                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_6                       : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_7                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_8                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_7                       : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_8                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_9                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_8                       : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_9                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_10                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_9                       : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_10                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_11                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_10                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_11                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_12                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_11                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_12                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_13                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_12                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_13                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_14                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_13                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_14                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_15                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_14                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_15                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_16                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_15                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_16                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_17                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_16                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_17                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_18                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_17                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_18                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_19                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_18                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_19                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_20                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_19                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_20                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_21                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_20                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_21                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_22                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_21                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_22                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_23                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_22                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_23                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_24                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_23                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_24                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_25                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_24                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_25                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_26                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_25                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_26                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_27                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_26                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_27                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_28                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_27                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_28                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_29                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_28                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_29                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_30                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_29                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_30                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_31                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_30                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_31                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_32                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_31                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_32                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_33                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_32                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_33                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_34                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_33                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_34                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_35                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_34                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_35                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum1_36                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_35                      : signed(38 DOWNTO 0); -- sfix39_En40
  SIGNAL sumpipe1_36                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_1                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_36                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_1                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_2                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_37                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_2                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_3                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_38                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_3                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_4                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_39                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_4                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_5                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_40                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_5                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_6                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_41                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_6                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_7                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_42                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_7                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_8                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_43                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_8                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_9                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_44                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_9                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_10                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_45                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_10                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_11                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_46                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_11                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_12                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_47                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_12                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_13                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_48                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_13                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_14                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_49                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_14                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_15                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_50                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_15                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_16                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_51                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_16                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_17                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_52                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_17                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum2_18                          : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_53                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe2_18                      : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum3_1                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_54                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe3_1                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum3_2                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_55                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe3_2                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum3_3                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_56                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe3_3                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum3_4                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_57                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe3_4                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum3_5                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_58                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe3_5                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum3_6                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_59                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe3_6                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum3_7                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_60                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe3_7                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum3_8                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_61                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe3_8                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum3_9                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_62                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe3_9                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum4_1                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_63                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe4_1                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum4_2                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_64                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe4_2                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum4_3                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_65                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe4_3                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum4_4                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_66                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe4_4                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sumpipe4_5                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum5_1                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_67                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe5_1                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum5_2                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_68                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe5_2                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sumpipe5_3                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum6_1                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_69                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe6_1                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sumpipe6_2                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL sum7_1                           : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL add_temp_70                      : signed(41 DOWNTO 0); -- sfix42_En40
  SIGNAL sumpipe7_1                       : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL output_typeconvert               : signed(40 DOWNTO 0); -- sfix41_En40
  SIGNAL output_register                  : signed(40 DOWNTO 0); -- sfix41_En40


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      delay_pipeline(0 TO 71) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 71) <= delay_pipeline(0 TO 70);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(71) * coeff72;
  product72 <= mul_temp(37 DOWNTO 0);

  mul_temp_1 <= delay_pipeline(70) * coeff71;
  product71 <= mul_temp_1(37 DOWNTO 0);

  mul_temp_2 <= delay_pipeline(69) * coeff70;
  product70 <= mul_temp_2(37 DOWNTO 0);

  mul_temp_3 <= delay_pipeline(68) * coeff69;
  product69 <= mul_temp_3(37 DOWNTO 0);

  mul_temp_4 <= delay_pipeline(67) * coeff68;
  product68 <= mul_temp_4(37 DOWNTO 0);

  mul_temp_5 <= delay_pipeline(66) * coeff67;
  product67 <= mul_temp_5(37 DOWNTO 0);

  mul_temp_6 <= delay_pipeline(65) * coeff66;
  product66 <= mul_temp_6(37 DOWNTO 0);

  mul_temp_7 <= delay_pipeline(64) * coeff65;
  product65 <= mul_temp_7(37 DOWNTO 0);

  mul_temp_8 <= delay_pipeline(63) * coeff64;
  product64 <= mul_temp_8(37 DOWNTO 0);

  mul_temp_9 <= delay_pipeline(62) * coeff63;
  product63 <= mul_temp_9(37 DOWNTO 0);

  mul_temp_10 <= delay_pipeline(61) * coeff62;
  product62 <= mul_temp_10(37 DOWNTO 0);

  mul_temp_11 <= delay_pipeline(60) * coeff61;
  product61 <= mul_temp_11(37 DOWNTO 0);

  mul_temp_12 <= delay_pipeline(59) * coeff60;
  product60 <= mul_temp_12(37 DOWNTO 0);

  mul_temp_13 <= delay_pipeline(58) * coeff59;
  product59 <= mul_temp_13(37 DOWNTO 0);

  mul_temp_14 <= delay_pipeline(57) * coeff58;
  product58 <= mul_temp_14(37 DOWNTO 0);

  mul_temp_15 <= delay_pipeline(56) * coeff57;
  product57 <= mul_temp_15(37 DOWNTO 0);

  mul_temp_16 <= delay_pipeline(55) * coeff56;
  product56 <= mul_temp_16(37 DOWNTO 0);

  mul_temp_17 <= delay_pipeline(54) * coeff55;
  product55 <= mul_temp_17(37 DOWNTO 0);

  mul_temp_18 <= delay_pipeline(53) * coeff54;
  product54 <= mul_temp_18(37 DOWNTO 0);

  mul_temp_19 <= delay_pipeline(52) * coeff53;
  product53 <= mul_temp_19(37 DOWNTO 0);

  mul_temp_20 <= delay_pipeline(51) * coeff52;
  product52 <= mul_temp_20(37 DOWNTO 0);

  mul_temp_21 <= delay_pipeline(50) * coeff51;
  product51 <= mul_temp_21(37 DOWNTO 0);

  mul_temp_22 <= delay_pipeline(49) * coeff50;
  product50 <= mul_temp_22(37 DOWNTO 0);

  mul_temp_23 <= delay_pipeline(48) * coeff49;
  product49 <= mul_temp_23(37 DOWNTO 0);

  mul_temp_24 <= delay_pipeline(47) * coeff48;
  product48 <= mul_temp_24(37 DOWNTO 0);

  mul_temp_25 <= delay_pipeline(46) * coeff47;
  product47 <= mul_temp_25(37 DOWNTO 0);

  mul_temp_26 <= delay_pipeline(45) * coeff46;
  product46 <= mul_temp_26(37 DOWNTO 0);

  mul_temp_27 <= delay_pipeline(44) * coeff45;
  product45 <= mul_temp_27(37 DOWNTO 0);

  mul_temp_28 <= delay_pipeline(43) * coeff44;
  product44 <= mul_temp_28(37 DOWNTO 0);

  mul_temp_29 <= delay_pipeline(42) * coeff43;
  product43 <= mul_temp_29(37 DOWNTO 0);

  mul_temp_30 <= delay_pipeline(41) * coeff42;
  product42 <= mul_temp_30(37 DOWNTO 0);

  mul_temp_31 <= delay_pipeline(40) * coeff41;
  product41 <= mul_temp_31(37 DOWNTO 0);

  mul_temp_32 <= delay_pipeline(39) * coeff40;
  product40 <= mul_temp_32(37 DOWNTO 0);

  mul_temp_33 <= delay_pipeline(38) * coeff39;
  product39 <= mul_temp_33(37 DOWNTO 0);

  mul_temp_34 <= delay_pipeline(37) * coeff38;
  product38 <= mul_temp_34(37 DOWNTO 0);

  mul_temp_35 <= delay_pipeline(36) * coeff37;
  product37 <= mul_temp_35(37 DOWNTO 0);

  mul_temp_36 <= delay_pipeline(35) * coeff36;
  product36 <= mul_temp_36(37 DOWNTO 0);

  mul_temp_37 <= delay_pipeline(34) * coeff35;
  product35 <= mul_temp_37(37 DOWNTO 0);

  mul_temp_38 <= delay_pipeline(33) * coeff34;
  product34 <= mul_temp_38(37 DOWNTO 0);

  mul_temp_39 <= delay_pipeline(32) * coeff33;
  product33 <= mul_temp_39(37 DOWNTO 0);

  mul_temp_40 <= delay_pipeline(31) * coeff32;
  product32 <= mul_temp_40(37 DOWNTO 0);

  mul_temp_41 <= delay_pipeline(30) * coeff31;
  product31 <= mul_temp_41(37 DOWNTO 0);

  mul_temp_42 <= delay_pipeline(29) * coeff30;
  product30 <= mul_temp_42(37 DOWNTO 0);

  mul_temp_43 <= delay_pipeline(28) * coeff29;
  product29 <= mul_temp_43(37 DOWNTO 0);

  mul_temp_44 <= delay_pipeline(27) * coeff28;
  product28 <= mul_temp_44(37 DOWNTO 0);

  mul_temp_45 <= delay_pipeline(26) * coeff27;
  product27 <= mul_temp_45(37 DOWNTO 0);

  mul_temp_46 <= delay_pipeline(25) * coeff26;
  product26 <= mul_temp_46(37 DOWNTO 0);

  mul_temp_47 <= delay_pipeline(24) * coeff25;
  product25 <= mul_temp_47(37 DOWNTO 0);

  mul_temp_48 <= delay_pipeline(23) * coeff24;
  product24 <= mul_temp_48(37 DOWNTO 0);

  mul_temp_49 <= delay_pipeline(22) * coeff23;
  product23 <= mul_temp_49(37 DOWNTO 0);

  mul_temp_50 <= delay_pipeline(21) * coeff22;
  product22 <= mul_temp_50(37 DOWNTO 0);

  mul_temp_51 <= delay_pipeline(20) * coeff21;
  product21 <= mul_temp_51(37 DOWNTO 0);

  mul_temp_52 <= delay_pipeline(19) * coeff20;
  product20 <= mul_temp_52(37 DOWNTO 0);

  mul_temp_53 <= delay_pipeline(18) * coeff19;
  product19 <= mul_temp_53(37 DOWNTO 0);

  mul_temp_54 <= delay_pipeline(17) * coeff18;
  product18 <= mul_temp_54(37 DOWNTO 0);

  mul_temp_55 <= delay_pipeline(16) * coeff17;
  product17 <= mul_temp_55(37 DOWNTO 0);

  mul_temp_56 <= delay_pipeline(15) * coeff16;
  product16 <= mul_temp_56(37 DOWNTO 0);

  mul_temp_57 <= delay_pipeline(14) * coeff15;
  product15 <= mul_temp_57(37 DOWNTO 0);

  mul_temp_58 <= delay_pipeline(13) * coeff14;
  product14 <= mul_temp_58(37 DOWNTO 0);

  mul_temp_59 <= delay_pipeline(12) * coeff13;
  product13 <= mul_temp_59(37 DOWNTO 0);

  mul_temp_60 <= delay_pipeline(11) * coeff12;
  product12 <= mul_temp_60(37 DOWNTO 0);

  mul_temp_61 <= delay_pipeline(10) * coeff11;
  product11 <= mul_temp_61(37 DOWNTO 0);

  mul_temp_62 <= delay_pipeline(9) * coeff10;
  product10 <= mul_temp_62(37 DOWNTO 0);

  mul_temp_63 <= delay_pipeline(8) * coeff9;
  product9 <= mul_temp_63(37 DOWNTO 0);

  mul_temp_64 <= delay_pipeline(7) * coeff8;
  product8 <= mul_temp_64(37 DOWNTO 0);

  mul_temp_65 <= delay_pipeline(6) * coeff7;
  product7 <= mul_temp_65(37 DOWNTO 0);

  mul_temp_66 <= delay_pipeline(5) * coeff6;
  product6 <= mul_temp_66(37 DOWNTO 0);

  mul_temp_67 <= delay_pipeline(4) * coeff5;
  product5 <= mul_temp_67(37 DOWNTO 0);

  mul_temp_68 <= delay_pipeline(3) * coeff4;
  product4 <= mul_temp_68(37 DOWNTO 0);

  mul_temp_69 <= delay_pipeline(2) * coeff3;
  product3 <= mul_temp_69(37 DOWNTO 0);

  mul_temp_70 <= delay_pipeline(1) * coeff2;
  product2 <= mul_temp_70(37 DOWNTO 0);

  mul_temp_71 <= delay_pipeline(0) * coeff1;
  product1 <= mul_temp_71(37 DOWNTO 0);

  add_temp <= resize(product72, 39) + resize(product71, 39);
  sum1_1 <= resize(add_temp, 41);

  add_temp_1 <= resize(product70, 39) + resize(product69, 39);
  sum1_2 <= resize(add_temp_1, 41);

  add_temp_2 <= resize(product68, 39) + resize(product67, 39);
  sum1_3 <= resize(add_temp_2, 41);

  add_temp_3 <= resize(product66, 39) + resize(product65, 39);
  sum1_4 <= resize(add_temp_3, 41);

  add_temp_4 <= resize(product64, 39) + resize(product63, 39);
  sum1_5 <= resize(add_temp_4, 41);

  add_temp_5 <= resize(product62, 39) + resize(product61, 39);
  sum1_6 <= resize(add_temp_5, 41);

  add_temp_6 <= resize(product60, 39) + resize(product59, 39);
  sum1_7 <= resize(add_temp_6, 41);

  add_temp_7 <= resize(product58, 39) + resize(product57, 39);
  sum1_8 <= resize(add_temp_7, 41);

  add_temp_8 <= resize(product56, 39) + resize(product55, 39);
  sum1_9 <= resize(add_temp_8, 41);

  add_temp_9 <= resize(product54, 39) + resize(product53, 39);
  sum1_10 <= resize(add_temp_9, 41);

  add_temp_10 <= resize(product52, 39) + resize(product51, 39);
  sum1_11 <= resize(add_temp_10, 41);

  add_temp_11 <= resize(product50, 39) + resize(product49, 39);
  sum1_12 <= resize(add_temp_11, 41);

  add_temp_12 <= resize(product48, 39) + resize(product47, 39);
  sum1_13 <= resize(add_temp_12, 41);

  add_temp_13 <= resize(product46, 39) + resize(product45, 39);
  sum1_14 <= resize(add_temp_13, 41);

  add_temp_14 <= resize(product44, 39) + resize(product43, 39);
  sum1_15 <= resize(add_temp_14, 41);

  add_temp_15 <= resize(product42, 39) + resize(product41, 39);
  sum1_16 <= resize(add_temp_15, 41);

  add_temp_16 <= resize(product40, 39) + resize(product39, 39);
  sum1_17 <= resize(add_temp_16, 41);

  add_temp_17 <= resize(product38, 39) + resize(product37, 39);
  sum1_18 <= resize(add_temp_17, 41);

  add_temp_18 <= resize(product36, 39) + resize(product35, 39);
  sum1_19 <= resize(add_temp_18, 41);

  add_temp_19 <= resize(product34, 39) + resize(product33, 39);
  sum1_20 <= resize(add_temp_19, 41);

  add_temp_20 <= resize(product32, 39) + resize(product31, 39);
  sum1_21 <= resize(add_temp_20, 41);

  add_temp_21 <= resize(product30, 39) + resize(product29, 39);
  sum1_22 <= resize(add_temp_21, 41);

  add_temp_22 <= resize(product28, 39) + resize(product27, 39);
  sum1_23 <= resize(add_temp_22, 41);

  add_temp_23 <= resize(product26, 39) + resize(product25, 39);
  sum1_24 <= resize(add_temp_23, 41);

  add_temp_24 <= resize(product24, 39) + resize(product23, 39);
  sum1_25 <= resize(add_temp_24, 41);

  add_temp_25 <= resize(product22, 39) + resize(product21, 39);
  sum1_26 <= resize(add_temp_25, 41);

  add_temp_26 <= resize(product20, 39) + resize(product19, 39);
  sum1_27 <= resize(add_temp_26, 41);

  add_temp_27 <= resize(product18, 39) + resize(product17, 39);
  sum1_28 <= resize(add_temp_27, 41);

  add_temp_28 <= resize(product16, 39) + resize(product15, 39);
  sum1_29 <= resize(add_temp_28, 41);

  add_temp_29 <= resize(product14, 39) + resize(product13, 39);
  sum1_30 <= resize(add_temp_29, 41);

  add_temp_30 <= resize(product12, 39) + resize(product11, 39);
  sum1_31 <= resize(add_temp_30, 41);

  add_temp_31 <= resize(product10, 39) + resize(product9, 39);
  sum1_32 <= resize(add_temp_31, 41);

  add_temp_32 <= resize(product8, 39) + resize(product7, 39);
  sum1_33 <= resize(add_temp_32, 41);

  add_temp_33 <= resize(product6, 39) + resize(product5, 39);
  sum1_34 <= resize(add_temp_33, 41);

  add_temp_34 <= resize(product4, 39) + resize(product3, 39);
  sum1_35 <= resize(add_temp_34, 41);

  add_temp_35 <= resize(product2, 39) + resize(product1, 39);
  sum1_36 <= resize(add_temp_35, 41);

  temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      sumpipe1_1 <= (OTHERS => '0');
      sumpipe1_2 <= (OTHERS => '0');
      sumpipe1_3 <= (OTHERS => '0');
      sumpipe1_4 <= (OTHERS => '0');
      sumpipe1_5 <= (OTHERS => '0');
      sumpipe1_6 <= (OTHERS => '0');
      sumpipe1_7 <= (OTHERS => '0');
      sumpipe1_8 <= (OTHERS => '0');
      sumpipe1_9 <= (OTHERS => '0');
      sumpipe1_10 <= (OTHERS => '0');
      sumpipe1_11 <= (OTHERS => '0');
      sumpipe1_12 <= (OTHERS => '0');
      sumpipe1_13 <= (OTHERS => '0');
      sumpipe1_14 <= (OTHERS => '0');
      sumpipe1_15 <= (OTHERS => '0');
      sumpipe1_16 <= (OTHERS => '0');
      sumpipe1_17 <= (OTHERS => '0');
      sumpipe1_18 <= (OTHERS => '0');
      sumpipe1_19 <= (OTHERS => '0');
      sumpipe1_20 <= (OTHERS => '0');
      sumpipe1_21 <= (OTHERS => '0');
      sumpipe1_22 <= (OTHERS => '0');
      sumpipe1_23 <= (OTHERS => '0');
      sumpipe1_24 <= (OTHERS => '0');
      sumpipe1_25 <= (OTHERS => '0');
      sumpipe1_26 <= (OTHERS => '0');
      sumpipe1_27 <= (OTHERS => '0');
      sumpipe1_28 <= (OTHERS => '0');
      sumpipe1_29 <= (OTHERS => '0');
      sumpipe1_30 <= (OTHERS => '0');
      sumpipe1_31 <= (OTHERS => '0');
      sumpipe1_32 <= (OTHERS => '0');
      sumpipe1_33 <= (OTHERS => '0');
      sumpipe1_34 <= (OTHERS => '0');
      sumpipe1_35 <= (OTHERS => '0');
      sumpipe1_36 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe1_1 <= sum1_1;
        sumpipe1_2 <= sum1_2;
        sumpipe1_3 <= sum1_3;
        sumpipe1_4 <= sum1_4;
        sumpipe1_5 <= sum1_5;
        sumpipe1_6 <= sum1_6;
        sumpipe1_7 <= sum1_7;
        sumpipe1_8 <= sum1_8;
        sumpipe1_9 <= sum1_9;
        sumpipe1_10 <= sum1_10;
        sumpipe1_11 <= sum1_11;
        sumpipe1_12 <= sum1_12;
        sumpipe1_13 <= sum1_13;
        sumpipe1_14 <= sum1_14;
        sumpipe1_15 <= sum1_15;
        sumpipe1_16 <= sum1_16;
        sumpipe1_17 <= sum1_17;
        sumpipe1_18 <= sum1_18;
        sumpipe1_19 <= sum1_19;
        sumpipe1_20 <= sum1_20;
        sumpipe1_21 <= sum1_21;
        sumpipe1_22 <= sum1_22;
        sumpipe1_23 <= sum1_23;
        sumpipe1_24 <= sum1_24;
        sumpipe1_25 <= sum1_25;
        sumpipe1_26 <= sum1_26;
        sumpipe1_27 <= sum1_27;
        sumpipe1_28 <= sum1_28;
        sumpipe1_29 <= sum1_29;
        sumpipe1_30 <= sum1_30;
        sumpipe1_31 <= sum1_31;
        sumpipe1_32 <= sum1_32;
        sumpipe1_33 <= sum1_33;
        sumpipe1_34 <= sum1_34;
        sumpipe1_35 <= sum1_35;
        sumpipe1_36 <= sum1_36;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  add_temp_36 <= resize(sumpipe1_1, 42) + resize(sumpipe1_2, 42);
  sum2_1 <= add_temp_36(40 DOWNTO 0);

  add_temp_37 <= resize(sumpipe1_3, 42) + resize(sumpipe1_4, 42);
  sum2_2 <= add_temp_37(40 DOWNTO 0);

  add_temp_38 <= resize(sumpipe1_5, 42) + resize(sumpipe1_6, 42);
  sum2_3 <= add_temp_38(40 DOWNTO 0);

  add_temp_39 <= resize(sumpipe1_7, 42) + resize(sumpipe1_8, 42);
  sum2_4 <= add_temp_39(40 DOWNTO 0);

  add_temp_40 <= resize(sumpipe1_9, 42) + resize(sumpipe1_10, 42);
  sum2_5 <= add_temp_40(40 DOWNTO 0);

  add_temp_41 <= resize(sumpipe1_11, 42) + resize(sumpipe1_12, 42);
  sum2_6 <= add_temp_41(40 DOWNTO 0);

  add_temp_42 <= resize(sumpipe1_13, 42) + resize(sumpipe1_14, 42);
  sum2_7 <= add_temp_42(40 DOWNTO 0);

  add_temp_43 <= resize(sumpipe1_15, 42) + resize(sumpipe1_16, 42);
  sum2_8 <= add_temp_43(40 DOWNTO 0);

  add_temp_44 <= resize(sumpipe1_17, 42) + resize(sumpipe1_18, 42);
  sum2_9 <= add_temp_44(40 DOWNTO 0);

  add_temp_45 <= resize(sumpipe1_19, 42) + resize(sumpipe1_20, 42);
  sum2_10 <= add_temp_45(40 DOWNTO 0);

  add_temp_46 <= resize(sumpipe1_21, 42) + resize(sumpipe1_22, 42);
  sum2_11 <= add_temp_46(40 DOWNTO 0);

  add_temp_47 <= resize(sumpipe1_23, 42) + resize(sumpipe1_24, 42);
  sum2_12 <= add_temp_47(40 DOWNTO 0);

  add_temp_48 <= resize(sumpipe1_25, 42) + resize(sumpipe1_26, 42);
  sum2_13 <= add_temp_48(40 DOWNTO 0);

  add_temp_49 <= resize(sumpipe1_27, 42) + resize(sumpipe1_28, 42);
  sum2_14 <= add_temp_49(40 DOWNTO 0);

  add_temp_50 <= resize(sumpipe1_29, 42) + resize(sumpipe1_30, 42);
  sum2_15 <= add_temp_50(40 DOWNTO 0);

  add_temp_51 <= resize(sumpipe1_31, 42) + resize(sumpipe1_32, 42);
  sum2_16 <= add_temp_51(40 DOWNTO 0);

  add_temp_52 <= resize(sumpipe1_33, 42) + resize(sumpipe1_34, 42);
  sum2_17 <= add_temp_52(40 DOWNTO 0);

  add_temp_53 <= resize(sumpipe1_35, 42) + resize(sumpipe1_36, 42);
  sum2_18 <= add_temp_53(40 DOWNTO 0);

  temp_process2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      sumpipe2_1 <= (OTHERS => '0');
      sumpipe2_2 <= (OTHERS => '0');
      sumpipe2_3 <= (OTHERS => '0');
      sumpipe2_4 <= (OTHERS => '0');
      sumpipe2_5 <= (OTHERS => '0');
      sumpipe2_6 <= (OTHERS => '0');
      sumpipe2_7 <= (OTHERS => '0');
      sumpipe2_8 <= (OTHERS => '0');
      sumpipe2_9 <= (OTHERS => '0');
      sumpipe2_10 <= (OTHERS => '0');
      sumpipe2_11 <= (OTHERS => '0');
      sumpipe2_12 <= (OTHERS => '0');
      sumpipe2_13 <= (OTHERS => '0');
      sumpipe2_14 <= (OTHERS => '0');
      sumpipe2_15 <= (OTHERS => '0');
      sumpipe2_16 <= (OTHERS => '0');
      sumpipe2_17 <= (OTHERS => '0');
      sumpipe2_18 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe2_1 <= sum2_1;
        sumpipe2_2 <= sum2_2;
        sumpipe2_3 <= sum2_3;
        sumpipe2_4 <= sum2_4;
        sumpipe2_5 <= sum2_5;
        sumpipe2_6 <= sum2_6;
        sumpipe2_7 <= sum2_7;
        sumpipe2_8 <= sum2_8;
        sumpipe2_9 <= sum2_9;
        sumpipe2_10 <= sum2_10;
        sumpipe2_11 <= sum2_11;
        sumpipe2_12 <= sum2_12;
        sumpipe2_13 <= sum2_13;
        sumpipe2_14 <= sum2_14;
        sumpipe2_15 <= sum2_15;
        sumpipe2_16 <= sum2_16;
        sumpipe2_17 <= sum2_17;
        sumpipe2_18 <= sum2_18;
      END IF;
    END IF; 
  END PROCESS temp_process2;

  add_temp_54 <= resize(sumpipe2_1, 42) + resize(sumpipe2_2, 42);
  sum3_1 <= add_temp_54(40 DOWNTO 0);

  add_temp_55 <= resize(sumpipe2_3, 42) + resize(sumpipe2_4, 42);
  sum3_2 <= add_temp_55(40 DOWNTO 0);

  add_temp_56 <= resize(sumpipe2_5, 42) + resize(sumpipe2_6, 42);
  sum3_3 <= add_temp_56(40 DOWNTO 0);

  add_temp_57 <= resize(sumpipe2_7, 42) + resize(sumpipe2_8, 42);
  sum3_4 <= add_temp_57(40 DOWNTO 0);

  add_temp_58 <= resize(sumpipe2_9, 42) + resize(sumpipe2_10, 42);
  sum3_5 <= add_temp_58(40 DOWNTO 0);

  add_temp_59 <= resize(sumpipe2_11, 42) + resize(sumpipe2_12, 42);
  sum3_6 <= add_temp_59(40 DOWNTO 0);

  add_temp_60 <= resize(sumpipe2_13, 42) + resize(sumpipe2_14, 42);
  sum3_7 <= add_temp_60(40 DOWNTO 0);

  add_temp_61 <= resize(sumpipe2_15, 42) + resize(sumpipe2_16, 42);
  sum3_8 <= add_temp_61(40 DOWNTO 0);

  add_temp_62 <= resize(sumpipe2_17, 42) + resize(sumpipe2_18, 42);
  sum3_9 <= add_temp_62(40 DOWNTO 0);

  temp_process3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      sumpipe3_1 <= (OTHERS => '0');
      sumpipe3_2 <= (OTHERS => '0');
      sumpipe3_3 <= (OTHERS => '0');
      sumpipe3_4 <= (OTHERS => '0');
      sumpipe3_5 <= (OTHERS => '0');
      sumpipe3_6 <= (OTHERS => '0');
      sumpipe3_7 <= (OTHERS => '0');
      sumpipe3_8 <= (OTHERS => '0');
      sumpipe3_9 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe3_1 <= sum3_1;
        sumpipe3_2 <= sum3_2;
        sumpipe3_3 <= sum3_3;
        sumpipe3_4 <= sum3_4;
        sumpipe3_5 <= sum3_5;
        sumpipe3_6 <= sum3_6;
        sumpipe3_7 <= sum3_7;
        sumpipe3_8 <= sum3_8;
        sumpipe3_9 <= sum3_9;
      END IF;
    END IF; 
  END PROCESS temp_process3;

  add_temp_63 <= resize(sumpipe3_1, 42) + resize(sumpipe3_2, 42);
  sum4_1 <= add_temp_63(40 DOWNTO 0);

  add_temp_64 <= resize(sumpipe3_3, 42) + resize(sumpipe3_4, 42);
  sum4_2 <= add_temp_64(40 DOWNTO 0);

  add_temp_65 <= resize(sumpipe3_5, 42) + resize(sumpipe3_6, 42);
  sum4_3 <= add_temp_65(40 DOWNTO 0);

  add_temp_66 <= resize(sumpipe3_7, 42) + resize(sumpipe3_8, 42);
  sum4_4 <= add_temp_66(40 DOWNTO 0);

  temp_process4 : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      sumpipe4_1 <= (OTHERS => '0');
      sumpipe4_2 <= (OTHERS => '0');
      sumpipe4_3 <= (OTHERS => '0');
      sumpipe4_4 <= (OTHERS => '0');
      sumpipe4_5 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe4_1 <= sum4_1;
        sumpipe4_2 <= sum4_2;
        sumpipe4_3 <= sum4_3;
        sumpipe4_4 <= sum4_4;
        sumpipe4_5 <= sumpipe3_9;
      END IF;
    END IF; 
  END PROCESS temp_process4;

  add_temp_67 <= resize(sumpipe4_1, 42) + resize(sumpipe4_2, 42);
  sum5_1 <= add_temp_67(40 DOWNTO 0);

  add_temp_68 <= resize(sumpipe4_3, 42) + resize(sumpipe4_4, 42);
  sum5_2 <= add_temp_68(40 DOWNTO 0);

  temp_process5 : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      sumpipe5_1 <= (OTHERS => '0');
      sumpipe5_2 <= (OTHERS => '0');
      sumpipe5_3 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe5_1 <= sum5_1;
        sumpipe5_2 <= sum5_2;
        sumpipe5_3 <= sumpipe4_5;
      END IF;
    END IF; 
  END PROCESS temp_process5;

  add_temp_69 <= resize(sumpipe5_1, 42) + resize(sumpipe5_2, 42);
  sum6_1 <= add_temp_69(40 DOWNTO 0);

  temp_process6 : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      sumpipe6_1 <= (OTHERS => '0');
      sumpipe6_2 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe6_1 <= sum6_1;
        sumpipe6_2 <= sumpipe5_3;
      END IF;
    END IF; 
  END PROCESS temp_process6;

  add_temp_70 <= resize(sumpipe6_1, 42) + resize(sumpipe6_2, 42);
  sum7_1 <= add_temp_70(40 DOWNTO 0);

  temp_process7 : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      sumpipe7_1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe7_1 <= sum7_1;
      END IF;
    END IF; 
  END PROCESS temp_process7;

  sum_final <= sumpipe7_1;

  output_typeconvert <= sum_final;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
