-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\magnitude\Complex_to_Magnitude_Angle_HDL_Optimized.vhd
-- Created: 2021-09-26 19:09:52
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Complex_to_Magnitude_Angle_HDL_Optimized
-- Source Path: magnitude/mag_cal/Complex to Magnitude-Angle HDL Optimized
-- Hierarchy Level: 1
-- 
-- Complex to Magnitude-Angle HDL Optimized
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Complex_to_Magnitude_Angle_HDL_Optimized IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In_re                             :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
        In_im                             :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
        validIn                           :   IN    std_logic;
        magnitude                         :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En15
        validOut                          :   OUT   std_logic
        );
END Complex_to_Magnitude_Angle_HDL_Optimized;


ARCHITECTURE rtl OF Complex_to_Magnitude_Angle_HDL_Optimized IS

  -- Component Declarations
  COMPONENT Quadrant_Mapper
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          xin                             :   IN    std_logic_vector(32 DOWNTO 0);  -- sfix33_En15
          yin                             :   IN    std_logic_vector(32 DOWNTO 0);  -- sfix33_En15
          xout                            :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En15
          yout                            :   OUT   std_logic_vector(32 DOWNTO 0)  -- sfix33_En15
          );
  END COMPONENT;

  COMPONENT CordicKernelMag
    PORT( xin                             :   IN    std_logic_vector(32 DOWNTO 0);  -- sfix33_En15
          yin                             :   IN    std_logic_vector(32 DOWNTO 0);  -- sfix33_En15
          idx                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          xout                            :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En15
          yout                            :   OUT   std_logic_vector(32 DOWNTO 0)  -- sfix33_En15
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Quadrant_Mapper
    USE ENTITY work.Quadrant_Mapper(rtl);

  FOR ALL : CordicKernelMag
    USE ENTITY work.CordicKernelMag(rtl);

  -- Signals
  SIGNAL Delay_ValidIn_reg                : std_logic_vector(0 TO 33);  -- ufix1 [34]
  SIGNAL ValidOutDelayed                  : std_logic;  -- ufix1
  SIGNAL In_re_signed                     : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL In_im_signed                     : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL qMapReal                         : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL qMapImag                         : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL In1Register                      : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL In2Register                      : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL XQMapped                         : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yQMapped                         : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL XQMapped_signed                  : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yQMapped_signed                  : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin1                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin1                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift1                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout1                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout1                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout1_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout1_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin2                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin2                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift2                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout2                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout2                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout2_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout2_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin3                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin3                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift3                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout3                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout3                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout3_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout3_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin4                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin4                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift4                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout4                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout4                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout4_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout4_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin5                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin5                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift5                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout5                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout5                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout5_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout5_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin6                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin6                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift6                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout6                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout6                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout6_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout6_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin7                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin7                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift7                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout7                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout7                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout7_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout7_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin8                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin8                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift8                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout8                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout8                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout8_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout8_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin9                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin9                             : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift9                           : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout9                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout9                            : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout9_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout9_signed                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin10                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin10                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift10                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout10                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout10                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout10_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout10_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin11                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin11                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift11                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout11                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout11                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout11_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout11_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin12                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin12                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift12                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout12                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout12                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout12_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout12_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin13                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin13                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift13                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout13                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout13                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout13_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout13_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin14                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin14                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift14                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout14                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout14                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout14_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout14_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin15                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin15                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift15                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout15                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout15                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout15_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout15_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin16                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin16                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift16                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout16                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout16                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout16_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout16_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin17                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin17                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift17                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout17                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout17                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout17_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout17_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin18                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin18                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift18                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout18                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout18                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout18_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout18_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin19                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin19                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift19                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout19                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout19                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout19_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout19_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin20                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin20                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift20                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout20                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout20                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout20_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout20_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin21                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin21                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift21                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout21                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout21                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout21_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout21_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin22                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin22                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift22                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout22                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout22                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout22_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout22_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin23                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin23                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift23                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout23                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout23                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout23_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout23_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin24                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin24                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift24                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout24                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout24                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout24_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout24_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin25                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin25                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift25                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout25                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout25                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout25_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout25_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin26                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin26                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift26                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout26                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout26                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout26_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout26_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin27                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin27                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift27                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout27                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout27                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout27_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout27_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin28                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin28                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift28                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout28                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout28                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout28_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout28_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin29                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin29                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift29                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout29                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout29                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout29_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout29_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin30                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin30                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift30                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout30                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout30                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout30_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout30_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin31                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yin31                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL shift31                          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL xout31                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL yout31                           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL xout31_signed                    : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL reset_1                          : std_logic;  -- ufix1
  SIGNAL xin32                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL CSD_Gain_Factor_mul_temp         : signed(48 DOWNTO 0);  -- sfix49_En30
  SIGNAL CSD_Gain_Factor_cast             : signed(47 DOWNTO 0);  -- sfix48_En30
  SIGNAL xoutscaled                       : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL zeroC                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL outSwitchMag                     : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xin33                            : signed(32 DOWNTO 0);  -- sfix33_En15

BEGIN
  u_QuadrantMapper : Quadrant_Mapper
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              xin => std_logic_vector(In1Register),  -- sfix33_En15
              yin => std_logic_vector(In2Register),  -- sfix33_En15
              xout => XQMapped,  -- sfix33_En15
              yout => yQMapped  -- sfix33_En15
              );

  u_Iteration : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin1),  -- sfix33_En15
              yin => std_logic_vector(yin1),  -- sfix33_En15
              idx => std_logic_vector(shift1),  -- ufix6
              xout => xout1,  -- sfix33_En15
              yout => yout1  -- sfix33_En15
              );

  u_Iteration_1 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin2),  -- sfix33_En15
              yin => std_logic_vector(yin2),  -- sfix33_En15
              idx => std_logic_vector(shift2),  -- ufix6
              xout => xout2,  -- sfix33_En15
              yout => yout2  -- sfix33_En15
              );

  u_Iteration_2 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin3),  -- sfix33_En15
              yin => std_logic_vector(yin3),  -- sfix33_En15
              idx => std_logic_vector(shift3),  -- ufix6
              xout => xout3,  -- sfix33_En15
              yout => yout3  -- sfix33_En15
              );

  u_Iteration_3 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin4),  -- sfix33_En15
              yin => std_logic_vector(yin4),  -- sfix33_En15
              idx => std_logic_vector(shift4),  -- ufix6
              xout => xout4,  -- sfix33_En15
              yout => yout4  -- sfix33_En15
              );

  u_Iteration_4 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin5),  -- sfix33_En15
              yin => std_logic_vector(yin5),  -- sfix33_En15
              idx => std_logic_vector(shift5),  -- ufix6
              xout => xout5,  -- sfix33_En15
              yout => yout5  -- sfix33_En15
              );

  u_Iteration_5 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin6),  -- sfix33_En15
              yin => std_logic_vector(yin6),  -- sfix33_En15
              idx => std_logic_vector(shift6),  -- ufix6
              xout => xout6,  -- sfix33_En15
              yout => yout6  -- sfix33_En15
              );

  u_Iteration_6 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin7),  -- sfix33_En15
              yin => std_logic_vector(yin7),  -- sfix33_En15
              idx => std_logic_vector(shift7),  -- ufix6
              xout => xout7,  -- sfix33_En15
              yout => yout7  -- sfix33_En15
              );

  u_Iteration_7 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin8),  -- sfix33_En15
              yin => std_logic_vector(yin8),  -- sfix33_En15
              idx => std_logic_vector(shift8),  -- ufix6
              xout => xout8,  -- sfix33_En15
              yout => yout8  -- sfix33_En15
              );

  u_Iteration_8 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin9),  -- sfix33_En15
              yin => std_logic_vector(yin9),  -- sfix33_En15
              idx => std_logic_vector(shift9),  -- ufix6
              xout => xout9,  -- sfix33_En15
              yout => yout9  -- sfix33_En15
              );

  u_Iteration_9 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin10),  -- sfix33_En15
              yin => std_logic_vector(yin10),  -- sfix33_En15
              idx => std_logic_vector(shift10),  -- ufix6
              xout => xout10,  -- sfix33_En15
              yout => yout10  -- sfix33_En15
              );

  u_Iteration_10 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin11),  -- sfix33_En15
              yin => std_logic_vector(yin11),  -- sfix33_En15
              idx => std_logic_vector(shift11),  -- ufix6
              xout => xout11,  -- sfix33_En15
              yout => yout11  -- sfix33_En15
              );

  u_Iteration_11 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin12),  -- sfix33_En15
              yin => std_logic_vector(yin12),  -- sfix33_En15
              idx => std_logic_vector(shift12),  -- ufix6
              xout => xout12,  -- sfix33_En15
              yout => yout12  -- sfix33_En15
              );

  u_Iteration_12 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin13),  -- sfix33_En15
              yin => std_logic_vector(yin13),  -- sfix33_En15
              idx => std_logic_vector(shift13),  -- ufix6
              xout => xout13,  -- sfix33_En15
              yout => yout13  -- sfix33_En15
              );

  u_Iteration_13 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin14),  -- sfix33_En15
              yin => std_logic_vector(yin14),  -- sfix33_En15
              idx => std_logic_vector(shift14),  -- ufix6
              xout => xout14,  -- sfix33_En15
              yout => yout14  -- sfix33_En15
              );

  u_Iteration_14 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin15),  -- sfix33_En15
              yin => std_logic_vector(yin15),  -- sfix33_En15
              idx => std_logic_vector(shift15),  -- ufix6
              xout => xout15,  -- sfix33_En15
              yout => yout15  -- sfix33_En15
              );

  u_Iteration_15 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin16),  -- sfix33_En15
              yin => std_logic_vector(yin16),  -- sfix33_En15
              idx => std_logic_vector(shift16),  -- ufix6
              xout => xout16,  -- sfix33_En15
              yout => yout16  -- sfix33_En15
              );

  u_Iteration_16 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin17),  -- sfix33_En15
              yin => std_logic_vector(yin17),  -- sfix33_En15
              idx => std_logic_vector(shift17),  -- ufix6
              xout => xout17,  -- sfix33_En15
              yout => yout17  -- sfix33_En15
              );

  u_Iteration_17 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin18),  -- sfix33_En15
              yin => std_logic_vector(yin18),  -- sfix33_En15
              idx => std_logic_vector(shift18),  -- ufix6
              xout => xout18,  -- sfix33_En15
              yout => yout18  -- sfix33_En15
              );

  u_Iteration_18 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin19),  -- sfix33_En15
              yin => std_logic_vector(yin19),  -- sfix33_En15
              idx => std_logic_vector(shift19),  -- ufix6
              xout => xout19,  -- sfix33_En15
              yout => yout19  -- sfix33_En15
              );

  u_Iteration_19 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin20),  -- sfix33_En15
              yin => std_logic_vector(yin20),  -- sfix33_En15
              idx => std_logic_vector(shift20),  -- ufix6
              xout => xout20,  -- sfix33_En15
              yout => yout20  -- sfix33_En15
              );

  u_Iteration_20 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin21),  -- sfix33_En15
              yin => std_logic_vector(yin21),  -- sfix33_En15
              idx => std_logic_vector(shift21),  -- ufix6
              xout => xout21,  -- sfix33_En15
              yout => yout21  -- sfix33_En15
              );

  u_Iteration_21 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin22),  -- sfix33_En15
              yin => std_logic_vector(yin22),  -- sfix33_En15
              idx => std_logic_vector(shift22),  -- ufix6
              xout => xout22,  -- sfix33_En15
              yout => yout22  -- sfix33_En15
              );

  u_Iteration_22 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin23),  -- sfix33_En15
              yin => std_logic_vector(yin23),  -- sfix33_En15
              idx => std_logic_vector(shift23),  -- ufix6
              xout => xout23,  -- sfix33_En15
              yout => yout23  -- sfix33_En15
              );

  u_Iteration_23 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin24),  -- sfix33_En15
              yin => std_logic_vector(yin24),  -- sfix33_En15
              idx => std_logic_vector(shift24),  -- ufix6
              xout => xout24,  -- sfix33_En15
              yout => yout24  -- sfix33_En15
              );

  u_Iteration_24 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin25),  -- sfix33_En15
              yin => std_logic_vector(yin25),  -- sfix33_En15
              idx => std_logic_vector(shift25),  -- ufix6
              xout => xout25,  -- sfix33_En15
              yout => yout25  -- sfix33_En15
              );

  u_Iteration_25 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin26),  -- sfix33_En15
              yin => std_logic_vector(yin26),  -- sfix33_En15
              idx => std_logic_vector(shift26),  -- ufix6
              xout => xout26,  -- sfix33_En15
              yout => yout26  -- sfix33_En15
              );

  u_Iteration_26 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin27),  -- sfix33_En15
              yin => std_logic_vector(yin27),  -- sfix33_En15
              idx => std_logic_vector(shift27),  -- ufix6
              xout => xout27,  -- sfix33_En15
              yout => yout27  -- sfix33_En15
              );

  u_Iteration_27 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin28),  -- sfix33_En15
              yin => std_logic_vector(yin28),  -- sfix33_En15
              idx => std_logic_vector(shift28),  -- ufix6
              xout => xout28,  -- sfix33_En15
              yout => yout28  -- sfix33_En15
              );

  u_Iteration_28 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin29),  -- sfix33_En15
              yin => std_logic_vector(yin29),  -- sfix33_En15
              idx => std_logic_vector(shift29),  -- ufix6
              xout => xout29,  -- sfix33_En15
              yout => yout29  -- sfix33_En15
              );

  u_Iteration_29 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin30),  -- sfix33_En15
              yin => std_logic_vector(yin30),  -- sfix33_En15
              idx => std_logic_vector(shift30),  -- ufix6
              xout => xout30,  -- sfix33_En15
              yout => yout30  -- sfix33_En15
              );

  u_Iteration_30 : CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin31),  -- sfix33_En15
              yin => std_logic_vector(yin31),  -- sfix33_En15
              idx => std_logic_vector(shift31),  -- ufix6
              xout => xout31,  -- sfix33_En15
              yout => yout31  -- sfix33_En15
              );

  Delay_ValidIn_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      Delay_ValidIn_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_ValidIn_reg(0) <= validIn;
        Delay_ValidIn_reg(1 TO 33) <= Delay_ValidIn_reg(0 TO 32);
      END IF;
    END IF;
  END PROCESS Delay_ValidIn_process;

  ValidOutDelayed <= Delay_ValidIn_reg(33);

  In_re_signed <= signed(In_re);

  qMapReal <= resize(In_re_signed, 33);

  In_im_signed <= signed(In_im);

  qMapImag <= resize(In_im_signed, 33);

  DelayRealInput_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      In1Register <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        In1Register <= qMapReal;
      END IF;
    END IF;
  END PROCESS DelayRealInput_process;


  DelayImagInput_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      In2Register <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        In2Register <= qMapImag;
      END IF;
    END IF;
  END PROCESS DelayImagInput_process;


  XQMapped_signed <= signed(XQMapped);

  yQMapped_signed <= signed(yQMapped);

  DelayQuadMapper1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin1 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin1 <= XQMapped_signed;
      END IF;
    END IF;
  END PROCESS DelayQuadMapper1_process;


  DelayQuadMapper2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin1 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin1 <= yQMapped_signed;
      END IF;
    END IF;
  END PROCESS DelayQuadMapper2_process;


  shift1 <= to_unsigned(16#01#, 6);

  xout1_signed <= signed(xout1);

  yout1_signed <= signed(yout1);

  Pipeline1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin2 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin2 <= xout1_signed;
      END IF;
    END IF;
  END PROCESS Pipeline1_process;


  Pipeline1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin2 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin2 <= yout1_signed;
      END IF;
    END IF;
  END PROCESS Pipeline1_1_process;


  shift2 <= to_unsigned(16#02#, 6);

  xout2_signed <= signed(xout2);

  yout2_signed <= signed(yout2);

  Pipeline2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin3 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin3 <= xout2_signed;
      END IF;
    END IF;
  END PROCESS Pipeline2_process;


  Pipeline2_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin3 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin3 <= yout2_signed;
      END IF;
    END IF;
  END PROCESS Pipeline2_1_process;


  shift3 <= to_unsigned(16#03#, 6);

  xout3_signed <= signed(xout3);

  yout3_signed <= signed(yout3);

  Pipeline3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin4 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin4 <= xout3_signed;
      END IF;
    END IF;
  END PROCESS Pipeline3_process;


  Pipeline3_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin4 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin4 <= yout3_signed;
      END IF;
    END IF;
  END PROCESS Pipeline3_1_process;


  shift4 <= to_unsigned(16#04#, 6);

  xout4_signed <= signed(xout4);

  yout4_signed <= signed(yout4);

  Pipeline4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin5 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin5 <= xout4_signed;
      END IF;
    END IF;
  END PROCESS Pipeline4_process;


  Pipeline4_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin5 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin5 <= yout4_signed;
      END IF;
    END IF;
  END PROCESS Pipeline4_1_process;


  shift5 <= to_unsigned(16#05#, 6);

  xout5_signed <= signed(xout5);

  yout5_signed <= signed(yout5);

  Pipeline5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin6 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin6 <= xout5_signed;
      END IF;
    END IF;
  END PROCESS Pipeline5_process;


  Pipeline5_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin6 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin6 <= yout5_signed;
      END IF;
    END IF;
  END PROCESS Pipeline5_1_process;


  shift6 <= to_unsigned(16#06#, 6);

  xout6_signed <= signed(xout6);

  yout6_signed <= signed(yout6);

  Pipeline6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin7 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin7 <= xout6_signed;
      END IF;
    END IF;
  END PROCESS Pipeline6_process;


  Pipeline6_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin7 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin7 <= yout6_signed;
      END IF;
    END IF;
  END PROCESS Pipeline6_1_process;


  shift7 <= to_unsigned(16#07#, 6);

  xout7_signed <= signed(xout7);

  yout7_signed <= signed(yout7);

  Pipeline7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin8 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin8 <= xout7_signed;
      END IF;
    END IF;
  END PROCESS Pipeline7_process;


  Pipeline7_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin8 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin8 <= yout7_signed;
      END IF;
    END IF;
  END PROCESS Pipeline7_1_process;


  shift8 <= to_unsigned(16#08#, 6);

  xout8_signed <= signed(xout8);

  yout8_signed <= signed(yout8);

  Pipeline8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin9 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin9 <= xout8_signed;
      END IF;
    END IF;
  END PROCESS Pipeline8_process;


  Pipeline8_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin9 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin9 <= yout8_signed;
      END IF;
    END IF;
  END PROCESS Pipeline8_1_process;


  shift9 <= to_unsigned(16#09#, 6);

  xout9_signed <= signed(xout9);

  yout9_signed <= signed(yout9);

  Pipeline9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin10 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin10 <= xout9_signed;
      END IF;
    END IF;
  END PROCESS Pipeline9_process;


  Pipeline9_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin10 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin10 <= yout9_signed;
      END IF;
    END IF;
  END PROCESS Pipeline9_1_process;


  shift10 <= to_unsigned(16#0A#, 6);

  xout10_signed <= signed(xout10);

  yout10_signed <= signed(yout10);

  Pipeline10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin11 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin11 <= xout10_signed;
      END IF;
    END IF;
  END PROCESS Pipeline10_process;


  Pipeline10_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin11 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin11 <= yout10_signed;
      END IF;
    END IF;
  END PROCESS Pipeline10_1_process;


  shift11 <= to_unsigned(16#0B#, 6);

  xout11_signed <= signed(xout11);

  yout11_signed <= signed(yout11);

  Pipeline11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin12 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin12 <= xout11_signed;
      END IF;
    END IF;
  END PROCESS Pipeline11_process;


  Pipeline11_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin12 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin12 <= yout11_signed;
      END IF;
    END IF;
  END PROCESS Pipeline11_1_process;


  shift12 <= to_unsigned(16#0C#, 6);

  xout12_signed <= signed(xout12);

  yout12_signed <= signed(yout12);

  Pipeline12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin13 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin13 <= xout12_signed;
      END IF;
    END IF;
  END PROCESS Pipeline12_process;


  Pipeline12_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin13 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin13 <= yout12_signed;
      END IF;
    END IF;
  END PROCESS Pipeline12_1_process;


  shift13 <= to_unsigned(16#0D#, 6);

  xout13_signed <= signed(xout13);

  yout13_signed <= signed(yout13);

  Pipeline13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin14 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin14 <= xout13_signed;
      END IF;
    END IF;
  END PROCESS Pipeline13_process;


  Pipeline13_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin14 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin14 <= yout13_signed;
      END IF;
    END IF;
  END PROCESS Pipeline13_1_process;


  shift14 <= to_unsigned(16#0E#, 6);

  xout14_signed <= signed(xout14);

  yout14_signed <= signed(yout14);

  Pipeline14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin15 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin15 <= xout14_signed;
      END IF;
    END IF;
  END PROCESS Pipeline14_process;


  Pipeline14_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin15 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin15 <= yout14_signed;
      END IF;
    END IF;
  END PROCESS Pipeline14_1_process;


  shift15 <= to_unsigned(16#0F#, 6);

  xout15_signed <= signed(xout15);

  yout15_signed <= signed(yout15);

  Pipeline15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin16 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin16 <= xout15_signed;
      END IF;
    END IF;
  END PROCESS Pipeline15_process;


  Pipeline15_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin16 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin16 <= yout15_signed;
      END IF;
    END IF;
  END PROCESS Pipeline15_1_process;


  shift16 <= to_unsigned(16#10#, 6);

  xout16_signed <= signed(xout16);

  yout16_signed <= signed(yout16);

  Pipeline16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin17 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin17 <= xout16_signed;
      END IF;
    END IF;
  END PROCESS Pipeline16_process;


  Pipeline16_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin17 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin17 <= yout16_signed;
      END IF;
    END IF;
  END PROCESS Pipeline16_1_process;


  shift17 <= to_unsigned(16#11#, 6);

  xout17_signed <= signed(xout17);

  yout17_signed <= signed(yout17);

  Pipeline17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin18 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin18 <= xout17_signed;
      END IF;
    END IF;
  END PROCESS Pipeline17_process;


  Pipeline17_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin18 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin18 <= yout17_signed;
      END IF;
    END IF;
  END PROCESS Pipeline17_1_process;


  shift18 <= to_unsigned(16#12#, 6);

  xout18_signed <= signed(xout18);

  yout18_signed <= signed(yout18);

  Pipeline18_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin19 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin19 <= xout18_signed;
      END IF;
    END IF;
  END PROCESS Pipeline18_process;


  Pipeline18_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin19 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin19 <= yout18_signed;
      END IF;
    END IF;
  END PROCESS Pipeline18_1_process;


  shift19 <= to_unsigned(16#13#, 6);

  xout19_signed <= signed(xout19);

  yout19_signed <= signed(yout19);

  Pipeline19_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin20 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin20 <= xout19_signed;
      END IF;
    END IF;
  END PROCESS Pipeline19_process;


  Pipeline19_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin20 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin20 <= yout19_signed;
      END IF;
    END IF;
  END PROCESS Pipeline19_1_process;


  shift20 <= to_unsigned(16#14#, 6);

  xout20_signed <= signed(xout20);

  yout20_signed <= signed(yout20);

  Pipeline20_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin21 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin21 <= xout20_signed;
      END IF;
    END IF;
  END PROCESS Pipeline20_process;


  Pipeline20_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin21 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin21 <= yout20_signed;
      END IF;
    END IF;
  END PROCESS Pipeline20_1_process;


  shift21 <= to_unsigned(16#15#, 6);

  xout21_signed <= signed(xout21);

  yout21_signed <= signed(yout21);

  Pipeline21_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin22 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin22 <= xout21_signed;
      END IF;
    END IF;
  END PROCESS Pipeline21_process;


  Pipeline21_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin22 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin22 <= yout21_signed;
      END IF;
    END IF;
  END PROCESS Pipeline21_1_process;


  shift22 <= to_unsigned(16#16#, 6);

  xout22_signed <= signed(xout22);

  yout22_signed <= signed(yout22);

  Pipeline22_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin23 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin23 <= xout22_signed;
      END IF;
    END IF;
  END PROCESS Pipeline22_process;


  Pipeline22_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin23 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin23 <= yout22_signed;
      END IF;
    END IF;
  END PROCESS Pipeline22_1_process;


  shift23 <= to_unsigned(16#17#, 6);

  xout23_signed <= signed(xout23);

  yout23_signed <= signed(yout23);

  Pipeline23_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin24 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin24 <= xout23_signed;
      END IF;
    END IF;
  END PROCESS Pipeline23_process;


  Pipeline23_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin24 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin24 <= yout23_signed;
      END IF;
    END IF;
  END PROCESS Pipeline23_1_process;


  shift24 <= to_unsigned(16#18#, 6);

  xout24_signed <= signed(xout24);

  yout24_signed <= signed(yout24);

  Pipeline24_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin25 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin25 <= xout24_signed;
      END IF;
    END IF;
  END PROCESS Pipeline24_process;


  Pipeline24_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin25 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin25 <= yout24_signed;
      END IF;
    END IF;
  END PROCESS Pipeline24_1_process;


  shift25 <= to_unsigned(16#19#, 6);

  xout25_signed <= signed(xout25);

  yout25_signed <= signed(yout25);

  Pipeline25_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin26 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin26 <= xout25_signed;
      END IF;
    END IF;
  END PROCESS Pipeline25_process;


  Pipeline25_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin26 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin26 <= yout25_signed;
      END IF;
    END IF;
  END PROCESS Pipeline25_1_process;


  shift26 <= to_unsigned(16#1A#, 6);

  xout26_signed <= signed(xout26);

  yout26_signed <= signed(yout26);

  Pipeline26_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin27 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin27 <= xout26_signed;
      END IF;
    END IF;
  END PROCESS Pipeline26_process;


  Pipeline26_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin27 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin27 <= yout26_signed;
      END IF;
    END IF;
  END PROCESS Pipeline26_1_process;


  shift27 <= to_unsigned(16#1B#, 6);

  xout27_signed <= signed(xout27);

  yout27_signed <= signed(yout27);

  Pipeline27_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin28 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin28 <= xout27_signed;
      END IF;
    END IF;
  END PROCESS Pipeline27_process;


  Pipeline27_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin28 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin28 <= yout27_signed;
      END IF;
    END IF;
  END PROCESS Pipeline27_1_process;


  shift28 <= to_unsigned(16#1C#, 6);

  xout28_signed <= signed(xout28);

  yout28_signed <= signed(yout28);

  Pipeline28_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin29 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin29 <= xout28_signed;
      END IF;
    END IF;
  END PROCESS Pipeline28_process;


  Pipeline28_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin29 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin29 <= yout28_signed;
      END IF;
    END IF;
  END PROCESS Pipeline28_1_process;


  shift29 <= to_unsigned(16#1D#, 6);

  xout29_signed <= signed(xout29);

  yout29_signed <= signed(yout29);

  Pipeline29_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin30 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin30 <= xout29_signed;
      END IF;
    END IF;
  END PROCESS Pipeline29_process;


  Pipeline29_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin30 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin30 <= yout29_signed;
      END IF;
    END IF;
  END PROCESS Pipeline29_1_process;


  shift30 <= to_unsigned(16#1E#, 6);

  xout30_signed <= signed(xout30);

  yout30_signed <= signed(yout30);

  Pipeline30_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin31 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin31 <= xout30_signed;
      END IF;
    END IF;
  END PROCESS Pipeline30_process;


  Pipeline30_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      yin31 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin31 <= yout30_signed;
      END IF;
    END IF;
  END PROCESS Pipeline30_1_process;


  shift31 <= to_unsigned(16#1F#, 6);

  xout31_signed <= signed(xout31);

  reset_1 <=  NOT ValidOutDelayed;

  Pipeline31_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin32 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin32 <= xout31_signed;
      END IF;
    END IF;
  END PROCESS Pipeline31_process;


  -- CSD Encoding (28141) : 1001'001'00001'01'01; Cost (Adders) = 5
  CSD_Gain_Factor_mul_temp <= ((((resize(xin32 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 49) - resize(xin32 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 49)) - resize(xin32 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 49)) - resize(xin32 & '0' & '0' & '0' & '0', 49)) - resize(xin32 & '0' & '0', 49)) + resize(xin32, 49);
  CSD_Gain_Factor_cast <= CSD_Gain_Factor_mul_temp(47 DOWNTO 0);
  xoutscaled <= CSD_Gain_Factor_cast(47 DOWNTO 15);

  zeroC <= to_signed(0, 33);

  
  outSwitchMag <= xoutscaled WHEN reset_1 = '0' ELSE
      zeroC;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      xin33 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin33 <= outSwitchMag;
      END IF;
    END IF;
  END PROCESS Output_Register_process;


  magnitude <= std_logic_vector(xin33);

  DelayValidOut_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      validOut <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        validOut <= ValidOutDelayed;
      END IF;
    END IF;
  END PROCESS DelayValidOut_process;


END rtl;

