-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\magnitude\CordicKernelMag.vhd
-- Created: 2021-09-26 19:09:52
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CordicKernelMag
-- Source Path: magnitude/mag_cal/Complex to Magnitude-Angle HDL Optimized/CordicKernelMag
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CordicKernelMag IS
  PORT( xin                               :   IN    std_logic_vector(32 DOWNTO 0);  -- sfix33_En15
        yin                               :   IN    std_logic_vector(32 DOWNTO 0);  -- sfix33_En15
        idx                               :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        xout                              :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En15
        yout                              :   OUT   std_logic_vector(32 DOWNTO 0)  -- sfix33_En15
        );
END CordicKernelMag;


ARCHITECTURE rtl OF CordicKernelMag IS

  -- Signals
  SIGNAL yin_signed                       : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yLessThanZero                    : std_logic;
  SIGNAL xin_signed                       : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL idx_unsigned                     : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL dynamic_shift_cast               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL yShifted                         : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xout2                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xout1                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL xout_tmp                         : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL dynamic_shift_cast_1             : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL xShifted                         : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout2                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout1                            : signed(32 DOWNTO 0);  -- sfix33_En15
  SIGNAL yout_tmp                         : signed(32 DOWNTO 0);  -- sfix33_En15

BEGIN
  yin_signed <= signed(yin);

  
  yLessThanZero <= '1' WHEN yin_signed < to_signed(0, 33) ELSE
      '0';

  xin_signed <= signed(xin);

  idx_unsigned <= unsigned(idx);

  dynamic_shift_cast <= resize(idx_unsigned, 8);
  yShifted <= SHIFT_RIGHT(yin_signed, to_integer(dynamic_shift_cast));

  xout2 <= xin_signed + yShifted;

  xout1 <= xin_signed - yShifted;

  
  xout_tmp <= xout2 WHEN yLessThanZero = '0' ELSE
      xout1;

  xout <= std_logic_vector(xout_tmp);

  dynamic_shift_cast_1 <= resize(idx_unsigned, 8);
  xShifted <= SHIFT_RIGHT(xin_signed, to_integer(dynamic_shift_cast_1));

  yout2 <= yin_signed - xShifted;

  yout1 <= yin_signed + xShifted;

  
  yout_tmp <= yout2 WHEN yLessThanZero = '0' ELSE
      yout1;

  yout <= std_logic_vector(yout_tmp);

END rtl;

