-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\magnitude\latency_pkg.vhd
-- Created: 2021-09-27 19:49:50
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE latency_pkg IS
  TYPE vector_of_unsigned6 IS ARRAY (NATURAL RANGE <>) OF unsigned(5 DOWNTO 0);
END latency_pkg;

