-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\magnitude\mag_cal.vhd
-- Created: 2021-09-26 19:09:52
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.1
-- Out2                          ce_out        0.1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mag_cal
-- Source Path: magnitude/mag_cal
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY mag_cal IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
        In2                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
        Input                             :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En15
        Out2                              :   OUT   std_logic
        );
END mag_cal;


ARCHITECTURE rtl OF mag_cal IS

  -- Component Declarations
  COMPONENT Complex_to_Magnitude_Angle_HDL_Optimized
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_re                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
          In_im                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
          validIn                         :   IN    std_logic;
          magnitude                       :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En15
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Complex_to_Magnitude_Angle_HDL_Optimized
    USE ENTITY work.Complex_to_Magnitude_Angle_HDL_Optimized(rtl);

  -- Signals
  SIGNAL Complex_to_Magnitude_Angle_HDL_Optimized_out1 : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL Complex_to_Magnitude_Angle_HDL_Optimized_out2 : std_logic;

BEGIN
  u_Complex_to_Magnitude_Angle_HDL_Optimized : Complex_to_Magnitude_Angle_HDL_Optimized
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              In_re => In1,  -- sfix32_En15
              In_im => In2,  -- sfix32_En15
              validIn => Input,
              magnitude => Complex_to_Magnitude_Angle_HDL_Optimized_out1,  -- sfix33_En15
              validOut => Complex_to_Magnitude_Angle_HDL_Optimized_out2
              );

  ce_out <= clk_enable;

  Out1 <= Complex_to_Magnitude_Angle_HDL_Optimized_out1;

  Out2 <= Complex_to_Magnitude_Angle_HDL_Optimized_out2;

END rtl;

