-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\taylor_sine\fakto.vhd
-- Created: 2021-02-11 17:00:00
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fakto
-- Source Path: taylor_sine/fakto
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY facto_calc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        reg_init                          :   IN    std_logic;
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END facto_calc;


ARCHITECTURE rtl OF facto_calc IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL HDL_Counter_out1                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Product_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Data_Type_Conversion1_out1       : unsigned(15 DOWNTO 0);  -- uint16

BEGIN


  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 7
  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      HDL_Counter_out1 <= to_unsigned(16#01#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN

        IF reg_init = '0' THEN 
            HDL_Counter_out1 <= to_unsigned(16#01#, 8);
        else
        
          IF HDL_Counter_out1 >= to_unsigned(16#07#, 8) THEN 
            HDL_Counter_out1 <= to_unsigned(16#01#, 8);
          ELSE 
            HDL_Counter_out1 <= HDL_Counter_out1 + to_unsigned(16#01#, 8);
          END IF;
          
        END IF;

    END IF;
  END PROCESS HDL_Counter_process;


  Product_out1 <= resize(Delay_out1 * HDL_Counter_out1, 32);

  Data_Type_Conversion1_out1 <= Product_out1(15 DOWNTO 0);

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      Delay_out1 <= to_unsigned(16#0001#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN

        if reg_init = '0' then
        Delay_out1 <= to_unsigned(16#0001#, 16);
        
        else
        Delay_out1 <= Data_Type_Conversion1_out1;

        end if;
        
    END IF;
  END PROCESS Delay_process;


  Out1 <= std_logic_vector(Delay_out1);


END rtl;

