-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\taylor_sine\pow1.vhd
-- Created: 2021-02-11 16:27:11
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: pow1
-- Source Path: taylor_sine/pow1
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY pow_calc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
        reg_init                          :   IN    std_logic;
        Out1                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En15
        );
END pow_calc;


ARCHITECTURE rtl OF pow_calc IS

  -- Signals

  SIGNAL In1_signed                       : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Delay_out1                       : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Product_out1                     : signed(63 DOWNTO 0);  -- sfix64_En30
  SIGNAL Data_Type_Conversion_out1        : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Delay_switch_delay               : signed(31 DOWNTO 0);  -- sfix32

BEGIN
  In1_signed <= signed(In1);

  Product_out1 <= Delay_out1 * In1_signed;

  Data_Type_Conversion_out1 <= Product_out1(46 DOWNTO 15);

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      Delay_switch_delay <= to_signed(32768, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
        IF reg_init = '0' THEN
          Delay_switch_delay <= to_signed(32768, 32);
        ELSE 
          Delay_switch_delay <= Data_Type_Conversion_out1;
        END IF;
    END IF;
  END PROCESS Delay_process;

  
  Delay_out1 <= to_signed(32768, 32) WHEN reg_init = '0' ELSE
      Delay_switch_delay;

  Out1 <= std_logic_vector(Delay_out1);



END rtl;

