-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\taylor_sine\pow1.vhd
-- Created: 2021-02-11 16:27:11
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: pow1
-- Source Path: taylor_sine/pow1
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY sum_calc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        term_data                         :   in    std_logic_vector(31 DOWNTO 0);
        in_ena                            :   in    std_logic;
        Out1                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En15sfix32_En15
        );
END sum_calc;


ARCHITECTURE rtl OF sum_calc IS

  signal in_ena_reg : std_logic := '0';
  -- Signals
  SIGNAL In1_signed                       : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL In3_signed                       : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL In2_signed                       : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Subtract_out1                    : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL In4_signed                       : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Subtract1_out1                   : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Sum_out1                         : signed(31 DOWNTO 0);  -- sfix32_En15

    type term_array is array (0 to 9) of std_logic_vector(31 downto 0);
    signal term_val : term_array ;
    signal i : integer := 0; 
    
BEGIN


  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      in_ena_reg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
       in_ena_reg <= in_ena;
    END IF;
  END PROCESS Delay_process;

  process(clk,reset)
  begin
  
      if reset='0' then
      i <= 0;
      elsif clk'event and clk='1' then
      
      if in_ena_reg = '1' then
      i <= i + 1;
      term_val(i) <= term_data;
      else
      i <= 0;
      end if;
      
      end if;
  
  end process;

  In1_signed <= signed(term_val(0));

  In3_signed <= signed(term_val(4));

  In2_signed <= signed(term_val(2));

  Subtract_out1 <= In1_signed - In2_signed;

  In4_signed <= signed(term_val(6));

  Subtract1_out1 <= In3_signed - In4_signed;

  Sum_out1 <= Subtract_out1 + Subtract1_out1;

  Out1 <= std_logic_vector(Sum_out1);


END rtl;

