-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\sine_fit\waveSUM.vhd
-- Created: 2020-10-29 10:09:31
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: waveSUM
-- Source Path: sine_fit/waveSUM 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY waveSUM IS
  PORT( In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
        In2                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END waveSUM;


ARCHITECTURE rtl OF waveSUM IS

  -- Signals
  SIGNAL In1_signed                       : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL In2_signed                       : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Add_out1                         : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Constant3_out1                   : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL Product_cast                     : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL Product_mul_temp                 : signed(39 DOWNTO 0);  -- sfix40_En15
  SIGNAL Product_out1                     : signed(38 DOWNTO 0);  -- sfix39_En15
  SIGNAL Constant4_out1                   : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL Add1_add_cast                    : signed(63 DOWNTO 0);  -- sfix64_En15
  SIGNAL Add1_add_cast_1                  : signed(63 DOWNTO 0);  -- sfix64_En15
  SIGNAL Add1_out1                        : signed(63 DOWNTO 0);  -- sfix64_En15
  SIGNAL Data_Type_Conversion_out1        : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  In1_signed <= signed(In1);

  In2_signed <= signed(In2);

  Add_out1 <= In1_signed + In2_signed;

  Constant3_out1 <= to_unsigned(16#3F#, 7);

  Product_cast <= signed(resize(Constant3_out1, 8));
  Product_mul_temp <= Add_out1 * Product_cast;
  Product_out1 <= Product_mul_temp(38 DOWNTO 0);

  Constant4_out1 <= to_unsigned(16#7F#, 7);

  Add1_add_cast <= resize(Product_out1, 64);
  Add1_add_cast_1 <= signed(resize(Constant4_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64));
  Add1_out1 <= Add1_add_cast + Add1_add_cast_1;

  Data_Type_Conversion_out1 <= unsigned(Add1_out1(22 DOWNTO 15));

  Out1 <= std_logic_vector(Data_Type_Conversion_out1);

END rtl;

