-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\sine_fit\sine_fit.vhd
-- Created: 2020-09-12 12:22:48
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: sine_fit
-- Source Path: sine_fit/sine_fit
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY sine_fit IS
  PORT( Input                             :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8_En7
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END sine_fit;


ARCHITECTURE rtl OF sine_fit IS

  -- Signals
  SIGNAL Input_signed                     : signed(7 DOWNTO 0);  -- sfix8_En7
  SIGNAL Constant_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Product_cast                     : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Product_mul_temp                 : signed(16 DOWNTO 0);  -- sfix17_En7
  SIGNAL Product_out1                     : signed(15 DOWNTO 0);  -- sfix16_En7
  SIGNAL Sum_add_cast                     : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL Sum_add_cast_1                   : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL Sum_add_temp                     : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL Sum_out1                         : signed(15 DOWNTO 0);  -- sfix16_En7
  SIGNAL Data_Type_Conversion_out1        : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  Input_signed <= signed(Input);

  Constant_out1 <= to_unsigned(16#80#, 8);

  Product_cast <= signed(resize(Constant_out1, 9));
  Product_mul_temp <= Input_signed * Product_cast;
  Product_out1 <= Product_mul_temp(15 DOWNTO 0);

  Sum_add_cast <= resize(Product_out1, 32);
  Sum_add_cast_1 <= signed(resize(Constant_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32));
  Sum_add_temp <= Sum_add_cast + Sum_add_cast_1;
  Sum_out1 <= Sum_add_temp(15 DOWNTO 0);

  Data_Type_Conversion_out1 <= unsigned(Sum_out1(14 DOWNTO 7));

  Out1 <= std_logic_vector(Data_Type_Conversion_out1);

END rtl;

