-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\product_ask\product_ask_demod.vhd
-- Created: 2021-09-03 11:30:19
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0
-- Target subsystem base rate: inf
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: product_ask_demod
-- Source Path: product_ask/product_ask_demod
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY product_ask_demod IS
  PORT( 
        clk                               :   in    std_logic;
        rst                               :   in    std_logic;
        ena                               :   in    std_logic;
        In1                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        In2                               :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
        Out1                              :   OUT   std_logic_vector(19 DOWNTO 0)  -- uint32
        );
END product_ask_demod;


ARCHITECTURE rtl OF product_ask_demod IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL In2_unsigned                     : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL Product_out1                     : unsigned(19 DOWNTO 0);  -- uint32

BEGIN
  In1_unsigned <= unsigned(In1);

  In2_unsigned <= unsigned(In2);

   process(clk, rst)
    begin
        if rst = '0' then
           
           Out1 <= (others => '0');
                 
        elsif rising_edge(clk) then
    
          Product_out1 <= resize(In1_unsigned * In2_unsigned, 20);
          Out1 <= std_logic_vector(Product_out1);
          
       end if;
       
    end process;

  

END rtl;

